// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafarSuite.ControlDesk.Infrastructure.Persistence.EntityFramework;

#nullable disable

namespace SafarSuite.ControlDesk.Infrastructure.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(ControlDeskDbContext))]
    [Migration("20260630194506_InitialClientPersistence")]
    partial class InitialClientPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("control")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SuspendedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_clients_code");

                    b.ToTable("clients", "control");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Clients.Client", b =>
                {
                    b.OwnsMany("SafarSuite.ControlDesk.Domain.Modules.Clients.ClientContact", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("client_contact_id");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<string>("Email")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("email");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("full_name");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean")
                                .HasColumnName("is_primary");

                            b1.Property<string>("JobTitle")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("job_title");

                            b1.Property<string>("Phone")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("phone");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("role");

                            b1.Property<Guid>("client_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("client_id", "Role")
                                .IsUnique()
                                .HasDatabaseName("ux_client_contacts_primary_role")
                                .HasFilter("is_primary");

                            b1.ToTable("client_contacts", "control");

                            b1.WithOwner()
                                .HasForeignKey("client_id");
                        });

                    b.OwnsMany("SafarSuite.ControlDesk.Domain.Modules.Clients.SupportNote", "SupportNotes", b1 =>
                        {
                            b1.Property<int>("support_note_row_id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("support_note_row_id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("support_note_row_id"));

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("created_by");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("text");

                            b1.Property<Guid>("client_id")
                                .HasColumnType("uuid");

                            b1.HasKey("support_note_row_id");

                            b1.HasIndex("client_id");

                            b1.ToTable("client_support_notes", "control");

                            b1.WithOwner()
                                .HasForeignKey("client_id");
                        });

                    b.Navigation("Contacts");

                    b.Navigation("SupportNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
