// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafarSuite.ControlDesk.Infrastructure.Persistence.EntityFramework;

#nullable disable

namespace SafarSuite.ControlDesk.Infrastructure.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(ControlDeskDbContext))]
    [Migration("20260630201044_AddAccountingPersistence")]
    partial class AddAccountingPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("control")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Accounting.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("Memo")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("memo");

                    b.Property<DateTimeOffset?>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at_utc");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_reference");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("VoidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("SourceType")
                        .HasDatabaseName("ix_journal_entries_source_type");

                    b.HasIndex("EntryDate", "CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_journal_entries_entry_date_created_id");

                    b.ToTable("journal_entries", "control");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Accounting.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsPostingAccount")
                        .HasColumnType("boolean")
                        .HasColumnName("is_posting_account");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("normal_balance");

                    b.Property<Guid?>("ParentAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_account_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_accounts_code");

                    b.HasIndex("ParentAccountId");

                    b.ToTable("ledger_accounts", "control");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SuspendedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_clients_code");

                    b.ToTable("clients", "control");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Accounting.JournalEntry", b =>
                {
                    b.OwnsMany("SafarSuite.ControlDesk.Domain.Modules.Accounting.JournalLine", "Lines", b1 =>
                        {
                            b1.Property<int>("journal_line_row_id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("journal_line_row_id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("journal_line_row_id"));

                            b1.Property<string>("Description")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("description");

                            b1.Property<Guid>("LedgerAccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("ledger_account_id");

                            b1.Property<Guid>("journal_entry_id")
                                .HasColumnType("uuid");

                            b1.HasKey("journal_line_row_id");

                            b1.HasIndex("LedgerAccountId")
                                .HasDatabaseName("ix_journal_lines_ledger_account_id");

                            b1.HasIndex("journal_entry_id");

                            b1.ToTable("journal_lines", "control");

                            b1.HasOne("SafarSuite.ControlDesk.Domain.Modules.Accounting.LedgerAccount", null)
                                .WithMany()
                                .HasForeignKey("LedgerAccountId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("journal_entry_id");

                            b1.OwnsOne("SafarSuite.ControlDesk.Domain.SharedKernel.Money", "Credit", b2 =>
                                {
                                    b2.Property<int>("JournalLinejournal_line_row_id")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("credit_amount");

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("credit_currency_code");

                                    b2.HasKey("JournalLinejournal_line_row_id");

                                    b2.ToTable("journal_lines", "control");

                                    b2.WithOwner()
                                        .HasForeignKey("JournalLinejournal_line_row_id");
                                });

                            b1.OwnsOne("SafarSuite.ControlDesk.Domain.SharedKernel.Money", "Debit", b2 =>
                                {
                                    b2.Property<int>("JournalLinejournal_line_row_id")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("debit_amount");

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("debit_currency_code");

                                    b2.HasKey("JournalLinejournal_line_row_id");

                                    b2.ToTable("journal_lines", "control");

                                    b2.WithOwner()
                                        .HasForeignKey("JournalLinejournal_line_row_id");
                                });

                            b1.Navigation("Credit")
                                .IsRequired();

                            b1.Navigation("Debit")
                                .IsRequired();
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Accounting.LedgerAccount", b =>
                {
                    b.HasOne("SafarSuite.ControlDesk.Domain.Modules.Accounting.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Clients.Client", b =>
                {
                    b.OwnsMany("SafarSuite.ControlDesk.Domain.Modules.Clients.ClientContact", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("client_contact_id");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<string>("Email")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("email");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("full_name");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean")
                                .HasColumnName("is_primary");

                            b1.Property<string>("JobTitle")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("job_title");

                            b1.Property<string>("Phone")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("phone");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("role");

                            b1.Property<Guid>("client_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("client_id", "Role")
                                .IsUnique()
                                .HasDatabaseName("ux_client_contacts_primary_role")
                                .HasFilter("is_primary");

                            b1.ToTable("client_contacts", "control");

                            b1.WithOwner()
                                .HasForeignKey("client_id");
                        });

                    b.OwnsMany("SafarSuite.ControlDesk.Domain.Modules.Clients.SupportNote", "SupportNotes", b1 =>
                        {
                            b1.Property<int>("support_note_row_id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("support_note_row_id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("support_note_row_id"));

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("created_by");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("text");

                            b1.Property<Guid>("client_id")
                                .HasColumnType("uuid");

                            b1.HasKey("support_note_row_id");

                            b1.HasIndex("client_id");

                            b1.ToTable("client_support_notes", "control");

                            b1.WithOwner()
                                .HasForeignKey("client_id");
                        });

                    b.Navigation("Contacts");

                    b.Navigation("SupportNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
