// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafarSuite.ControlDesk.Infrastructure.Persistence.EntityFramework;

#nullable disable

namespace SafarSuite.ControlDesk.Infrastructure.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(ControlDeskDbContext))]
    [Migration("20260701005304_AddEntitlementSnapshotPersistence")]
    partial class AddEntitlementSnapshotPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("control")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Accounting.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("Memo")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("memo");

                    b.Property<DateTimeOffset?>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at_utc");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_reference");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("VoidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("SourceType")
                        .HasDatabaseName("ix_journal_entries_source_type");

                    b.HasIndex("EntryDate", "CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_journal_entries_entry_date_created_id");

                    b.ToTable("journal_entries", "control");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Accounting.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsPostingAccount")
                        .HasColumnType("boolean")
                        .HasColumnName("is_posting_account");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("normal_balance");

                    b.Property<Guid?>("ParentAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_account_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_accounts_code");

                    b.HasIndex("ParentAccountId");

                    b.ToTable("ledger_accounts", "control");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Billing.ChargeCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_code_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("RevenueAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("revenue_account_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaxAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("tax_account_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_charge_codes_code");

                    b.HasIndex("RevenueAccountId");

                    b.HasIndex("TaxAccountId");

                    b.ToTable("charge_codes", "control");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Billing.ClientChargeRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("client_charge_rule_id");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("billing_cycle");

                    b.Property<int>("BillingDayOfMonth")
                        .HasColumnType("integer")
                        .HasColumnName("billing_day_of_month");

                    b.Property<Guid>("ChargeCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_code_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DescriptionOverride")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description_override");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ChargeCodeId")
                        .HasDatabaseName("ix_client_charge_rules_charge_code_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_charge_rules_client_id");

                    b.ToTable("client_charge_rules", "control");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Billing.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_invoices_client_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ux_invoices_number");

                    b.ToTable("invoices", "control");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SuspendedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_clients_code");

                    b.ToTable("clients", "control");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Clients.ClientAccountingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("client_accounting_profile_id");

                    b.Property<Guid>("AccountsReceivableAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accounts_receivable_account_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("CloudCustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("cloud_customer_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefaultCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("default_currency_code");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AccountsReceivableAccountId");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("ux_client_accounting_profiles_client_id");

                    b.ToTable("client_accounting_profiles", "control");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.ControlCloud.CloudOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("cloud_outbox_message_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at_utc");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("subject_type");

                    b.HasKey("Id");

                    b.HasIndex("Status", "MessageType", "OccurredAtUtc")
                        .HasDatabaseName("ix_cloud_outbox_messages_status_type_occurred");

                    b.ToTable("cloud_outbox_messages", "control");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Entitlements.EntitlementSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("entitlement_snapshot_id");

                    b.Property<int>("AllowedBranches")
                        .HasColumnType("integer")
                        .HasColumnName("allowed_branches");

                    b.Property<int>("AllowedDevices")
                        .HasColumnType("integer")
                        .HasColumnName("allowed_devices");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateOnly>("GraceUntil")
                        .HasColumnType("date")
                        .HasColumnName("grace_until");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<DateOnly>("OfflineValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("offline_valid_until");

                    b.Property<DateOnly>("PaidUntil")
                        .HasColumnType("date")
                        .HasColumnName("paid_until");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "IssuedAtUtc")
                        .HasDatabaseName("ix_entitlement_snapshots_client_issued");

                    b.ToTable("entitlement_snapshots", "control");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("decision_note");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("method");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date")
                        .HasColumnName("received_on");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_payments_client_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_payments_invoice_id");

                    b.HasIndex("Reference")
                        .HasDatabaseName("ix_payments_reference");

                    b.ToTable("payments", "control");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Accounting.JournalEntry", b =>
                {
                    b.OwnsMany("SafarSuite.ControlDesk.Domain.Modules.Accounting.JournalLine", "Lines", b1 =>
                        {
                            b1.Property<int>("journal_line_row_id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("journal_line_row_id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("journal_line_row_id"));

                            b1.Property<string>("Description")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("description");

                            b1.Property<Guid>("LedgerAccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("ledger_account_id");

                            b1.Property<Guid>("journal_entry_id")
                                .HasColumnType("uuid");

                            b1.HasKey("journal_line_row_id");

                            b1.HasIndex("LedgerAccountId")
                                .HasDatabaseName("ix_journal_lines_ledger_account_id");

                            b1.HasIndex("journal_entry_id");

                            b1.ToTable("journal_lines", "control");

                            b1.HasOne("SafarSuite.ControlDesk.Domain.Modules.Accounting.LedgerAccount", null)
                                .WithMany()
                                .HasForeignKey("LedgerAccountId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("journal_entry_id");

                            b1.OwnsOne("SafarSuite.ControlDesk.Domain.SharedKernel.Money", "Credit", b2 =>
                                {
                                    b2.Property<int>("JournalLinejournal_line_row_id")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("credit_amount");

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("credit_currency_code");

                                    b2.HasKey("JournalLinejournal_line_row_id");

                                    b2.ToTable("journal_lines", "control");

                                    b2.WithOwner()
                                        .HasForeignKey("JournalLinejournal_line_row_id");
                                });

                            b1.OwnsOne("SafarSuite.ControlDesk.Domain.SharedKernel.Money", "Debit", b2 =>
                                {
                                    b2.Property<int>("JournalLinejournal_line_row_id")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("debit_amount");

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("debit_currency_code");

                                    b2.HasKey("JournalLinejournal_line_row_id");

                                    b2.ToTable("journal_lines", "control");

                                    b2.WithOwner()
                                        .HasForeignKey("JournalLinejournal_line_row_id");
                                });

                            b1.Navigation("Credit")
                                .IsRequired();

                            b1.Navigation("Debit")
                                .IsRequired();
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Accounting.LedgerAccount", b =>
                {
                    b.HasOne("SafarSuite.ControlDesk.Domain.Modules.Accounting.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Billing.ChargeCode", b =>
                {
                    b.HasOne("SafarSuite.ControlDesk.Domain.Modules.Accounting.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("RevenueAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafarSuite.ControlDesk.Domain.Modules.Accounting.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("TaxAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("SafarSuite.ControlDesk.Domain.SharedKernel.Money", "DefaultUnitPrice", b1 =>
                        {
                            b1.Property<Guid>("ChargeCodeId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("default_unit_price_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("default_unit_price_currency_code");

                            b1.HasKey("ChargeCodeId");

                            b1.ToTable("charge_codes", "control");

                            b1.WithOwner()
                                .HasForeignKey("ChargeCodeId");
                        });

                    b.Navigation("DefaultUnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Billing.ClientChargeRule", b =>
                {
                    b.HasOne("SafarSuite.ControlDesk.Domain.Modules.Billing.ChargeCode", null)
                        .WithMany()
                        .HasForeignKey("ChargeCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafarSuite.ControlDesk.Domain.Modules.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SafarSuite.ControlDesk.Domain.SharedKernel.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("ClientChargeRuleId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("unit_price_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("unit_price_currency_code");

                            b1.HasKey("ClientChargeRuleId");

                            b1.ToTable("client_charge_rules", "control");

                            b1.WithOwner()
                                .HasForeignKey("ClientChargeRuleId");
                        });

                    b.OwnsOne("SafarSuite.ControlDesk.Domain.SharedKernel.DateRange", "EffectivePeriod", b1 =>
                        {
                            b1.Property<Guid>("ClientChargeRuleId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("EndsOn")
                                .HasColumnType("date")
                                .HasColumnName("effective_ends_on");

                            b1.Property<DateOnly>("StartsOn")
                                .HasColumnType("date")
                                .HasColumnName("effective_starts_on");

                            b1.HasKey("ClientChargeRuleId");

                            b1.ToTable("client_charge_rules", "control");

                            b1.WithOwner()
                                .HasForeignKey("ClientChargeRuleId");
                        });

                    b.Navigation("EffectivePeriod")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Billing.Invoice", b =>
                {
                    b.HasOne("SafarSuite.ControlDesk.Domain.Modules.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SafarSuite.ControlDesk.Domain.SharedKernel.Money", "AmountPaid", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount_paid_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_paid_currency_code");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("invoices", "control");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.OwnsMany("SafarSuite.ControlDesk.Domain.Modules.Billing.InvoiceLine", "Lines", b1 =>
                        {
                            b1.Property<int>("invoice_line_row_id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("invoice_line_row_id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("invoice_line_row_id"));

                            b1.Property<Guid?>("ChargeCodeId")
                                .HasColumnType("uuid")
                                .HasColumnName("charge_code_id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("description");

                            b1.Property<Guid>("invoice_id")
                                .HasColumnType("uuid");

                            b1.HasKey("invoice_line_row_id");

                            b1.HasIndex("ChargeCodeId")
                                .HasDatabaseName("ix_invoice_lines_charge_code_id");

                            b1.HasIndex("invoice_id");

                            b1.ToTable("invoice_lines", "control");

                            b1.HasOne("SafarSuite.ControlDesk.Domain.Modules.Billing.ChargeCode", null)
                                .WithMany()
                                .HasForeignKey("ChargeCodeId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.WithOwner()
                                .HasForeignKey("invoice_id");

                            b1.OwnsOne("SafarSuite.ControlDesk.Domain.SharedKernel.Money", "Amount", b2 =>
                                {
                                    b2.Property<int>("InvoiceLineinvoice_line_row_id")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("amount");

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("currency_code");

                                    b2.HasKey("InvoiceLineinvoice_line_row_id");

                                    b2.ToTable("invoice_lines", "control");

                                    b2.WithOwner()
                                        .HasForeignKey("InvoiceLineinvoice_line_row_id");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.Navigation("AmountPaid")
                        .IsRequired();

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Clients.Client", b =>
                {
                    b.OwnsMany("SafarSuite.ControlDesk.Domain.Modules.Clients.ClientContact", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("client_contact_id");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<string>("Email")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("email");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("full_name");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean")
                                .HasColumnName("is_primary");

                            b1.Property<string>("JobTitle")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("job_title");

                            b1.Property<string>("Phone")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("phone");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("role");

                            b1.Property<Guid>("client_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("client_id", "Role")
                                .IsUnique()
                                .HasDatabaseName("ux_client_contacts_primary_role")
                                .HasFilter("is_primary");

                            b1.ToTable("client_contacts", "control");

                            b1.WithOwner()
                                .HasForeignKey("client_id");
                        });

                    b.OwnsMany("SafarSuite.ControlDesk.Domain.Modules.Clients.SupportNote", "SupportNotes", b1 =>
                        {
                            b1.Property<int>("support_note_row_id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("support_note_row_id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("support_note_row_id"));

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("created_by");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("text");

                            b1.Property<Guid>("client_id")
                                .HasColumnType("uuid");

                            b1.HasKey("support_note_row_id");

                            b1.HasIndex("client_id");

                            b1.ToTable("client_support_notes", "control");

                            b1.WithOwner()
                                .HasForeignKey("client_id");
                        });

                    b.Navigation("Contacts");

                    b.Navigation("SupportNotes");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Clients.ClientAccountingProfile", b =>
                {
                    b.HasOne("SafarSuite.ControlDesk.Domain.Modules.Accounting.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountsReceivableAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafarSuite.ControlDesk.Domain.Modules.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Entitlements.EntitlementSnapshot", b =>
                {
                    b.HasOne("SafarSuite.ControlDesk.Domain.Modules.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("SafarSuite.ControlDesk.Domain.Modules.Entitlements.EntitlementModule", "Modules", b1 =>
                        {
                            b1.Property<int>("entitlement_snapshot_module_row_id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("entitlement_snapshot_module_row_id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("entitlement_snapshot_module_row_id"));

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("is_enabled");

                            b1.Property<string>("ModuleCode")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("module_code");

                            b1.Property<Guid>("entitlement_snapshot_id")
                                .HasColumnType("uuid");

                            b1.HasKey("entitlement_snapshot_module_row_id");

                            b1.HasIndex("entitlement_snapshot_id", "ModuleCode")
                                .IsUnique()
                                .HasDatabaseName("ux_entitlement_snapshot_modules_snapshot_code");

                            b1.ToTable("entitlement_snapshot_modules", "control");

                            b1.WithOwner()
                                .HasForeignKey("entitlement_snapshot_id");
                        });

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("SafarSuite.ControlDesk.Domain.Modules.Payments.Payment", b =>
                {
                    b.HasOne("SafarSuite.ControlDesk.Domain.Modules.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafarSuite.ControlDesk.Domain.Modules.Billing.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SafarSuite.ControlDesk.Domain.SharedKernel.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency_code");

                            b1.HasKey("PaymentId");

                            b1.ToTable("payments", "control");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
