// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(ControlCloudDbContext))]
    [Migration("20260702183000_AddInstallationDeploymentProfile")]
    partial class AddInstallationDeploymentProfile
    {
    }
}
