// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework;

#nullable disable

namespace SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(ControlCloudDbContext))]
    [Migration("20260701165250_AddControlCloudPersistence")]
    partial class AddControlCloudPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cloud")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientCommercialProjectionEntity", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<string>("ProjectionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("projection_json");

                    b.HasKey("ClientId");

                    b.HasIndex("LastUpdatedAtUtc")
                        .HasDatabaseName("ix_client_commercial_projections_last_updated_at_utc");

                    b.ToTable("client_commercial_projections", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlDeskEnvelopeReceiptEntity", b =>
                {
                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<string>("CloudReference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cloud_reference");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTimeOffset>("PreparedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prepared_at_utc");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("SignatureKeyId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("signature_key_id");

                    b.Property<string>("SignatureValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("signature_value");

                    b.Property<string>("SourceEnvironment")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_environment");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("subject_type");

                    b.HasKey("ReceiptId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_control_desk_envelope_receipts_accepted_idempotency_key")
                        .HasFilter("status = 'Accepted'");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_control_desk_envelope_receipts_message_id");

                    b.HasIndex("Status", "IdempotencyKey")
                        .HasDatabaseName("ix_control_desk_envelope_receipts_status_idempotency_key");

                    b.ToTable("control_desk_envelope_receipts", "cloud");
                });
#pragma warning restore 612, 618
        }
    }
}
