// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework;

#nullable disable

namespace SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(ControlCloudDbContext))]
    [Migration("20260708180759_AddBootstrapPackageRegisterMetadata")]
    partial class AddBootstrapPackageRegisterMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cloud")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientCommercialProjectionEntity", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<string>("ProjectionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("projection_json");

                    b.HasKey("ClientId");

                    b.HasIndex("LastUpdatedAtUtc")
                        .HasDatabaseName("ix_client_commercial_projections_last_updated_at_utc");

                    b.ToTable("client_commercial_projections", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientInstallationEntity", b =>
                {
                    b.Property<string>("InstallationId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<string>("BootstrapMode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("bootstrap_mode");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("branch_code");

                    b.Property<string>("ClientDeploymentMode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("client_deployment_mode");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("LastBundleIssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_bundle_issued_at_utc");

                    b.Property<long>("LatestEntitlementVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("latest_entitlement_version");

                    b.Property<string>("ParentSiteId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("parent_site_id");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<string>("SiteId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("site_id");

                    b.Property<string>("SiteRole")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("site_role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SyncTopologyId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("sync_topology_id");

                    b.HasKey("InstallationId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_installations_client_id");

                    b.ToTable("client_installations", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientPortalInvitationEntity", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<Guid?>("AcceptedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_user_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset>("InvitedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at_utc");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("InvitationId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_client_portal_invitations_token_hash");

                    b.HasIndex("ClientId", "NormalizedEmail", "Status")
                        .HasDatabaseName("ix_client_portal_invitations_client_email_status");

                    b.ToTable("client_portal_invitations", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientPortalUserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("UserId");

                    b.HasIndex("ClientId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_client_portal_users_client_email");

                    b.HasIndex("ClientId", "Status")
                        .HasDatabaseName("ix_client_portal_users_client_status");

                    b.ToTable("client_portal_users", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudEntitlementBundleIssueEntity", b =>
                {
                    b.Property<Guid>("BundleIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("bundle_issue_id");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("algorithm");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("EntitlementSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("entitlement_snapshot_id");

                    b.Property<long>("EntitlementVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("entitlement_version");

                    b.Property<DateOnly>("GraceUntil")
                        .HasColumnType("date")
                        .HasColumnName("grace_until");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("key_id");

                    b.Property<DateOnly>("OfflineValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("offline_valid_until");

                    b.Property<DateOnly>("PaidUntil")
                        .HasColumnType("date")
                        .HasColumnName("paid_until");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_sha256");

                    b.Property<string>("SignatureValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("signature_value");

                    b.Property<DateOnly>("WarningStartsAt")
                        .HasColumnType("date")
                        .HasColumnName("warning_starts_at");

                    b.HasKey("BundleIssueId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_entitlement_bundle_issues_client_id");

                    b.HasIndex("InstallationId")
                        .HasDatabaseName("ix_entitlement_bundle_issues_installation_id");

                    b.HasIndex("InstallationId", "EntitlementVersion")
                        .HasDatabaseName("ix_entitlement_bundle_issues_installation_version");

                    b.ToTable("entitlement_bundle_issues", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationCommandAcknowledgementEntity", b =>
                {
                    b.Property<Guid>("AcknowledgementId")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledgement_id");

                    b.Property<DateTimeOffset>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<long>("CommandVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("command_version");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result_status");

                    b.HasKey("AcknowledgementId");

                    b.HasIndex("CommandId")
                        .HasDatabaseName("ix_installation_command_acknowledgements_command_id");

                    b.HasIndex("InstallationId")
                        .HasDatabaseName("ix_installation_command_acknowledgements_installation_id");

                    b.ToTable("installation_command_acknowledgements", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationCommandEntity", b =>
                {
                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<DateTimeOffset?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<string>("AcknowledgementDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("acknowledgement_detail");

                    b.Property<string>("AcknowledgementStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("acknowledgement_status");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("command_type");

                    b.Property<long>("CommandVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("command_version");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset?>("NotBeforeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_sha256");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at_utc");

                    b.Property<string>("SignatureAlgorithm")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("signature_algorithm");

                    b.Property<string>("SignatureKeyId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("signature_key_id");

                    b.Property<string>("SignatureValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("signature_value");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("CommandId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_installation_commands_client_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_installation_commands_idempotency_key");

                    b.HasIndex("InstallationId", "CommandVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_installation_commands_installation_version");

                    b.HasIndex("InstallationId", "Status")
                        .HasDatabaseName("ix_installation_commands_installation_status");

                    b.ToTable("installation_commands", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationDiagnosticReportEntity", b =>
                {
                    b.Property<Guid>("DiagnosticReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_report_id");

                    b.Property<string>("BundleJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("bundle_json");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at_utc");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<string>("LicenseStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("license_status");

                    b.Property<string>("LocalServerVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("local_server_version");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("DiagnosticReportId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_installation_diagnostic_reports_client_id");

                    b.HasIndex("InstallationId", "ReceivedAtUtc")
                        .HasDatabaseName("ix_installation_diagnostic_reports_installation_received");

                    b.ToTable("installation_diagnostic_reports", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationHeartbeatEntity", b =>
                {
                    b.Property<Guid>("HeartbeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("heartbeat_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<long?>("EntitlementVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("entitlement_version");

                    b.Property<DateOnly?>("GraceUntil")
                        .HasColumnType("date")
                        .HasColumnName("grace_until");

                    b.Property<string>("HeartbeatStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("heartbeat_status");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<string>("LicenseStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("license_status");

                    b.Property<string>("LocalServerVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("local_server_version");

                    b.Property<DateOnly?>("OfflineValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("offline_valid_until");

                    b.Property<DateOnly?>("PaidUntil")
                        .HasColumnType("date")
                        .HasColumnName("paid_until");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<DateTimeOffset>("ReportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at_utc");

                    b.Property<DateOnly?>("WarningStartsAt")
                        .HasColumnType("date")
                        .HasColumnName("warning_starts_at");

                    b.HasKey("HeartbeatId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_installation_heartbeats_client_id");

                    b.HasIndex("InstallationId", "LicenseStatus")
                        .HasDatabaseName("ix_installation_heartbeats_installation_license_status");

                    b.HasIndex("InstallationId", "ReceivedAtUtc")
                        .HasDatabaseName("ix_installation_heartbeats_installation_received_at");

                    b.ToTable("installation_heartbeats", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationSetupTokenEntity", b =>
                {
                    b.Property<Guid>("SetupTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("setup_token_id");

                    b.Property<DateTimeOffset?>("BootstrapPackageGeneratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bootstrap_package_generated_at_utc");

                    b.Property<Guid?>("BootstrapPackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("bootstrap_package_id");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("branch_code");

                    b.Property<string>("ClientDeploymentMode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("client_deployment_mode");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<string>("ConsumedLocalServerVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("consumed_local_server_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<string>("DeploymentMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("deployment_mode");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<string>("PackageBundleFileName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("package_bundle_file_name");

                    b.Property<string>("PackageBundleSha256")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("package_bundle_sha256");

                    b.Property<string>("PackageLocalServerVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("package_local_server_version");

                    b.Property<string>("PackageSafarSuiteAppVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("package_safar_suite_app_version");

                    b.Property<string>("ParentSiteId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("parent_site_id");

                    b.Property<string>("SiteId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("site_id");

                    b.Property<string>("SiteRole")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("site_role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SyncTopologyId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("sync_topology_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("SetupTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_installation_setup_tokens_token_hash");

                    b.HasIndex("ClientId", "InstallationId", "BootstrapPackageGeneratedAtUtc")
                        .HasDatabaseName("ix_installation_setup_tokens_bootstrap_package_register");

                    b.HasIndex("ClientId", "InstallationId", "Status")
                        .HasDatabaseName("ix_installation_setup_tokens_client_installation_status");

                    b.ToTable("installation_setup_tokens", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudProviderAccessOperatorEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempt_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LastFailedLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_failed_login_at_utc");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<DateTimeOffset?>("LastRecoveryCodeUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_recovery_code_used_at_utc");

                    b.Property<long?>("LastTotpStep")
                        .HasColumnType("bigint")
                        .HasColumnName("last_totp_step");

                    b.Property<DateTimeOffset?>("LastTotpUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_totp_used_at_utc");

                    b.Property<DateTimeOffset?>("LockoutEndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_ends_at_utc");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RecoveryCodeHashesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recovery_code_hashes_json");

                    b.Property<DateTimeOffset?>("RecoveryCodesUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recovery_codes_updated_at_utc");

                    b.Property<string>("RecoveryCodesUpdatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("recovery_codes_updated_by");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scopes_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TotpEnabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("totp_enabled_at_utc");

                    b.Property<string>("TotpSecret")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("totp_secret");

                    b.Property<DateTimeOffset?>("TotpUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("totp_updated_at_utc");

                    b.Property<string>("TotpUpdatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("totp_updated_by");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("updated_by");

                    b.HasKey("UserId");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_provider_access_operators_email");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_provider_access_operators_status");

                    b.ToTable("provider_access_operators", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlDeskEnvelopeReceiptEntity", b =>
                {
                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<string>("CloudReference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cloud_reference");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTimeOffset>("PreparedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prepared_at_utc");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("SignatureKeyId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("signature_key_id");

                    b.Property<string>("SignatureValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("signature_value");

                    b.Property<string>("SourceEnvironment")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_environment");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("subject_type");

                    b.HasKey("ReceiptId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_control_desk_envelope_receipts_accepted_idempotency_key")
                        .HasFilter("status = 'Accepted'");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_control_desk_envelope_receipts_message_id");

                    b.HasIndex("Status", "IdempotencyKey")
                        .HasDatabaseName("ix_control_desk_envelope_receipts_status_idempotency_key");

                    b.ToTable("control_desk_envelope_receipts", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudEntitlementBundleIssueEntity", b =>
                {
                    b.HasOne("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientInstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationCommandAcknowledgementEntity", b =>
                {
                    b.HasOne("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationCommandEntity", null)
                        .WithMany()
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationCommandEntity", b =>
                {
                    b.HasOne("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientInstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationDiagnosticReportEntity", b =>
                {
                    b.HasOne("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientInstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationHeartbeatEntity", b =>
                {
                    b.HasOne("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientInstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
