// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework;

#nullable disable

namespace SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(ControlCloudDbContext))]
    [Migration("20260713221145_AddClientPortalPaymentBoundary")]
    partial class AddClientPortalPaymentBoundary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cloud")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientCommercialProjectionEntity", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<decimal>("AvailableCredit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("available_credit");

                    b.Property<decimal>("BalanceDue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance_due");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<DateTimeOffset>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<string>("LatestEntitlementJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("latest_entitlement_json");

                    b.Property<decimal>("TotalCreditApplied")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_credit_applied");

                    b.Property<decimal>("TotalCredited")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_credited");

                    b.Property<decimal>("TotalInvoiced")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_invoiced");

                    b.Property<decimal>("TotalPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_paid");

                    b.Property<decimal>("TotalRefunded")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_refunded");

                    b.HasKey("ClientId");

                    b.HasIndex("LastUpdatedAtUtc")
                        .HasDatabaseName("ix_client_commercial_projections_last_updated_at_utc");

                    b.ToTable("client_commercial_projections", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientInstallationEntity", b =>
                {
                    b.Property<string>("InstallationId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<string>("BootstrapMode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("bootstrap_mode");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("branch_code");

                    b.Property<string>("ClientDeploymentMode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("client_deployment_mode");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("LastBundleIssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_bundle_issued_at_utc");

                    b.Property<long>("LatestEntitlementVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("latest_entitlement_version");

                    b.Property<string>("ParentSiteId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("parent_site_id");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<string>("SiteId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("site_id");

                    b.Property<string>("SiteRole")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("site_role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SyncTopologyId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("sync_topology_id");

                    b.HasKey("InstallationId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_installations_client_id");

                    b.ToTable("client_installations", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientPortalAttachmentEntity", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("AttachmentId");

                    b.HasIndex("ClientId", "UploadedAtUtc")
                        .HasDatabaseName("ix_client_portal_attachments_client_uploaded");

                    b.ToTable("client_portal_attachments", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientPortalInvitationEntity", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<Guid?>("AcceptedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_user_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset>("InvitedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at_utc");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("InvitationId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_client_portal_invitations_token_hash");

                    b.HasIndex("ClientId", "NormalizedEmail", "Status")
                        .HasDatabaseName("ix_client_portal_invitations_client_email_status");

                    b.ToTable("client_portal_invitations", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientPortalMailDeliveryEntity", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at_utc");

                    b.Property<DateTimeOffset?>("LastAttemptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempted_at_utc");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("recipient_email");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("recipient_name");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("subject");

                    b.Property<string>("TextBody")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("text_body");

                    b.HasKey("DeliveryId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_portal_mail_deliveries_client_id");

                    b.HasIndex("Status", "LeaseExpiresAtUtc")
                        .HasDatabaseName("ix_client_portal_mail_deliveries_status_lease_expiry");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_client_portal_mail_deliveries_status_next_attempt");

                    b.ToTable("client_portal_mail_deliveries", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientPortalPasswordResetEntity", b =>
                {
                    b.Property<Guid>("PasswordResetId")
                        .HasColumnType("uuid")
                        .HasColumnName("password_reset_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("PasswordResetId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_client_portal_password_resets_token_hash");

                    b.HasIndex("UserId", "ExpiresAtUtc")
                        .HasDatabaseName("ix_client_portal_password_resets_user_expiry");

                    b.ToTable("client_portal_password_resets", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientPortalPaymentClaimEntity", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("invoice_number");

                    b.Property<string>("NormalizedTransferReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("normalized_transfer_reference_number");

                    b.Property<Guid?>("ProofAttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("proof_attachment_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_user_id");

                    b.Property<string>("TransferReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("transfer_reference_number");

                    b.Property<Guid?>("VerifiedPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_payment_id");

                    b.HasKey("ClaimId");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_client_portal_payment_claims_invoice_id");

                    b.HasIndex("ClientId", "NormalizedTransferReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_client_portal_payment_claims_client_reference");

                    b.HasIndex("ClientId", "Status", "SubmittedAtUtc")
                        .HasDatabaseName("ix_client_portal_payment_claims_client_status_submitted");

                    b.ToTable("client_portal_payment_claims", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientPortalSessionEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at_utc");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("IdleExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("idle_expires_at_utc");

                    b.Property<DateTimeOffset>("LastActivityAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at_utc");

                    b.Property<string>("PreviousRefreshTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("previous_refresh_token_hash");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<int>("SecurityVersion")
                        .HasColumnType("integer")
                        .HasColumnName("security_version");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId");

                    b.HasIndex("IdleExpiresAtUtc")
                        .HasDatabaseName("ix_client_portal_sessions_idle_expiry");

                    b.HasIndex("PreviousRefreshTokenHash")
                        .HasDatabaseName("ix_client_portal_sessions_previous_refresh_hash");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_client_portal_sessions_refresh_hash");

                    b.HasIndex("UserId", "RevokedAtUtc")
                        .HasDatabaseName("ix_client_portal_sessions_user_revoked");

                    b.ToTable("client_portal_sessions", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientPortalUserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<DateTimeOffset?>("LastRecoveryCodeUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_recovery_code_used_at_utc");

                    b.Property<long?>("LastTotpStep")
                        .HasColumnType("bigint")
                        .HasColumnName("last_totp_step");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PendingProtectedTotpSecret")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("pending_protected_totp_secret");

                    b.Property<string>("PendingRecoveryCodeHashesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("pending_recovery_code_hashes_json");

                    b.Property<string>("ProtectedTotpSecret")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("protected_totp_secret");

                    b.Property<string>("RecoveryCodeHashesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("recovery_code_hashes_json");

                    b.Property<DateTimeOffset?>("RecoveryCodesGeneratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recovery_codes_generated_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<int>("SecurityVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("security_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TotpEnabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("totp_enabled_at_utc");

                    b.Property<DateTimeOffset?>("TotpEnrollmentStartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("totp_enrollment_started_at_utc");

                    b.HasKey("UserId");

                    b.HasIndex("ClientId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_client_portal_users_client_email");

                    b.HasIndex("ClientId", "Status")
                        .HasDatabaseName("ix_client_portal_users_client_status");

                    b.ToTable("client_portal_users", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudCommercialDocumentEntity", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("document_type");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance_amount");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<DateOnly>("DocumentDate")
                        .HasColumnType("date")
                        .HasColumnName("document_date");

                    b.Property<Guid>("LastMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_message_id");

                    b.Property<DateTimeOffset>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("reference");

                    b.Property<Guid?>("RelatedDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_document_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.HasKey("ClientId", "DocumentType", "DocumentId");

                    b.HasIndex("ClientId", "DocumentType", "DocumentDate", "DocumentId")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_commercial_documents_client_type_date_id");

                    b.HasIndex("ClientId", "DocumentType", "RelatedDocumentId", "DocumentDate", "DocumentId")
                        .IsDescending(false, false, false, true, true)
                        .HasDatabaseName("ix_commercial_documents_related_date_id");

                    b.ToTable("commercial_documents", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudEntitlementBundleIssueEntity", b =>
                {
                    b.Property<Guid>("BundleIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("bundle_issue_id");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("algorithm");

                    b.Property<int?>("AllowedConcurrentUsers")
                        .HasColumnType("integer")
                        .HasColumnName("allowed_concurrent_users");

                    b.Property<int?>("AllowedNamedUsers")
                        .HasColumnType("integer")
                        .HasColumnName("allowed_named_users");

                    b.Property<Guid>("ClientAccessRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_access_revision_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<long>("ContractRevisionNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("contract_revision_number");

                    b.Property<Guid>("EntitlementSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("entitlement_snapshot_id");

                    b.Property<long>("EntitlementVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("entitlement_version");

                    b.Property<int>("FeatureLimitCount")
                        .HasColumnType("integer")
                        .HasColumnName("feature_limit_count");

                    b.Property<DateOnly>("GraceUntil")
                        .HasColumnType("date")
                        .HasColumnName("grace_until");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("key_id");

                    b.Property<DateOnly>("OfflineValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("offline_valid_until");

                    b.Property<DateOnly>("PaidUntil")
                        .HasColumnType("date")
                        .HasColumnName("paid_until");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_sha256");

                    b.Property<Guid>("ProductCatalogRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_catalog_revision_id");

                    b.Property<long>("ProductCatalogRevisionNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("product_catalog_revision_number");

                    b.Property<string>("SignatureValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("signature_value");

                    b.Property<DateOnly>("WarningStartsAt")
                        .HasColumnType("date")
                        .HasColumnName("warning_starts_at");

                    b.HasKey("BundleIssueId");

                    b.HasIndex("ClientAccessRevisionId")
                        .HasDatabaseName("ix_entitlement_bundle_issues_access_revision");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_entitlement_bundle_issues_client_id");

                    b.HasIndex("InstallationId")
                        .HasDatabaseName("ix_entitlement_bundle_issues_installation_id");

                    b.HasIndex("ProductCatalogRevisionId")
                        .HasDatabaseName("ix_entitlement_bundle_issues_product_catalog_revision");

                    b.HasIndex("InstallationId", "EntitlementVersion")
                        .HasDatabaseName("ix_entitlement_bundle_issues_installation_version");

                    b.ToTable("entitlement_bundle_issues", "cloud", t =>
                        {
                            t.HasCheckConstraint("ck_entitlement_bundle_issues_concurrent_users", "allowed_concurrent_users IS NULL OR allowed_concurrent_users >= 0");

                            t.HasCheckConstraint("ck_entitlement_bundle_issues_feature_limit_count", "feature_limit_count >= 0");

                            t.HasCheckConstraint("ck_entitlement_bundle_issues_named_users", "allowed_named_users IS NULL OR allowed_named_users >= 0");

                            t.HasCheckConstraint("ck_entitlement_bundle_issues_user_limit_order", "allowed_named_users IS NULL OR allowed_concurrent_users IS NULL OR allowed_concurrent_users <= allowed_named_users");
                        });
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationCommandAcknowledgementEntity", b =>
                {
                    b.Property<Guid>("AcknowledgementId")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledgement_id");

                    b.Property<DateTimeOffset>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<long>("CommandVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("command_version");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result_status");

                    b.HasKey("AcknowledgementId");

                    b.HasIndex("CommandId")
                        .HasDatabaseName("ix_installation_command_acknowledgements_command_id");

                    b.HasIndex("InstallationId")
                        .HasDatabaseName("ix_installation_command_acknowledgements_installation_id");

                    b.ToTable("installation_command_acknowledgements", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationCommandEntity", b =>
                {
                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<DateTimeOffset?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<string>("AcknowledgementDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("acknowledgement_detail");

                    b.Property<string>("AcknowledgementStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("acknowledgement_status");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("command_type");

                    b.Property<long>("CommandVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("command_version");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset?>("NotBeforeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_sha256");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at_utc");

                    b.Property<string>("SignatureAlgorithm")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("signature_algorithm");

                    b.Property<string>("SignatureKeyId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("signature_key_id");

                    b.Property<string>("SignatureValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("signature_value");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("CommandId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_installation_commands_client_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_installation_commands_idempotency_key");

                    b.HasIndex("InstallationId", "CommandVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_installation_commands_installation_version");

                    b.HasIndex("InstallationId", "Status")
                        .HasDatabaseName("ix_installation_commands_installation_status");

                    b.ToTable("installation_commands", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationDiagnosticReportEntity", b =>
                {
                    b.Property<Guid>("DiagnosticReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_report_id");

                    b.Property<string>("BundleJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("bundle_json");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at_utc");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<string>("LicenseStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("license_status");

                    b.Property<string>("LocalServerVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("local_server_version");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("DiagnosticReportId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_installation_diagnostic_reports_client_id");

                    b.HasIndex("InstallationId", "ReceivedAtUtc")
                        .HasDatabaseName("ix_installation_diagnostic_reports_installation_received");

                    b.ToTable("installation_diagnostic_reports", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationHeartbeatEntity", b =>
                {
                    b.Property<Guid>("HeartbeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("heartbeat_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<long?>("EntitlementVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("entitlement_version");

                    b.Property<DateOnly?>("GraceUntil")
                        .HasColumnType("date")
                        .HasColumnName("grace_until");

                    b.Property<string>("HeartbeatStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("heartbeat_status");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<string>("LicenseStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("license_status");

                    b.Property<string>("LocalServerVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("local_server_version");

                    b.Property<string>("ObservedEntitlementStateJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("observed_entitlement_state_json");

                    b.Property<DateOnly?>("OfflineValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("offline_valid_until");

                    b.Property<DateOnly?>("PaidUntil")
                        .HasColumnType("date")
                        .HasColumnName("paid_until");

                    b.Property<int?>("PairingApprovedDeviceCount")
                        .HasColumnType("integer")
                        .HasColumnName("pairing_approved_device_count");

                    b.Property<bool?>("PairingFirstManagerDeviceApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("pairing_first_manager_device_approved");

                    b.Property<DateTimeOffset?>("PairingFirstManagerDeviceApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pairing_first_manager_device_approved_at_utc");

                    b.Property<DateTimeOffset?>("PairingLastDeviceUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pairing_last_device_updated_at_utc");

                    b.Property<string>("PairingMode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("pairing_mode");

                    b.Property<int?>("PairingPendingDeviceCount")
                        .HasColumnType("integer")
                        .HasColumnName("pairing_pending_device_count");

                    b.Property<int?>("PairingRevokedDeviceCount")
                        .HasColumnType("integer")
                        .HasColumnName("pairing_revoked_device_count");

                    b.Property<int?>("PairingSuspendedDeviceCount")
                        .HasColumnType("integer")
                        .HasColumnName("pairing_suspended_device_count");

                    b.Property<int?>("PairingTotalDeviceCount")
                        .HasColumnType("integer")
                        .HasColumnName("pairing_total_device_count");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<DateTimeOffset>("ReportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at_utc");

                    b.Property<DateOnly?>("WarningStartsAt")
                        .HasColumnType("date")
                        .HasColumnName("warning_starts_at");

                    b.HasKey("HeartbeatId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_installation_heartbeats_client_id");

                    b.HasIndex("InstallationId", "LicenseStatus")
                        .HasDatabaseName("ix_installation_heartbeats_installation_license_status");

                    b.HasIndex("InstallationId", "ReceivedAtUtc")
                        .HasDatabaseName("ix_installation_heartbeats_installation_received_at");

                    b.ToTable("installation_heartbeats", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationSetupTokenEntity", b =>
                {
                    b.Property<Guid>("SetupTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("setup_token_id");

                    b.Property<DateTimeOffset?>("BootstrapPackageGeneratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bootstrap_package_generated_at_utc");

                    b.Property<Guid?>("BootstrapPackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("bootstrap_package_id");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("branch_code");

                    b.Property<string>("ClientDeploymentMode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("client_deployment_mode");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<string>("ConsumedLocalServerVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("consumed_local_server_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<string>("DeploymentMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("deployment_mode");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<string>("PackageBundleFileName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("package_bundle_file_name");

                    b.Property<string>("PackageBundleSha256")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("package_bundle_sha256");

                    b.Property<string>("PackageLocalServerVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("package_local_server_version");

                    b.Property<string>("PackageSafarSuiteAppVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("package_safar_suite_app_version");

                    b.Property<string>("ParentSiteId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("parent_site_id");

                    b.Property<string>("SiteId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("site_id");

                    b.Property<string>("SiteRole")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("site_role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SyncTopologyId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("sync_topology_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("SetupTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_installation_setup_tokens_token_hash");

                    b.HasIndex("ClientId", "InstallationId", "BootstrapPackageGeneratedAtUtc")
                        .HasDatabaseName("ix_installation_setup_tokens_bootstrap_package_register");

                    b.HasIndex("ClientId", "InstallationId", "Status")
                        .HasDatabaseName("ix_installation_setup_tokens_client_installation_status");

                    b.ToTable("installation_setup_tokens", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudProviderAccessOperatorEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempt_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LastFailedLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_failed_login_at_utc");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<DateTimeOffset?>("LastRecoveryCodeUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_recovery_code_used_at_utc");

                    b.Property<long?>("LastTotpStep")
                        .HasColumnType("bigint")
                        .HasColumnName("last_totp_step");

                    b.Property<DateTimeOffset?>("LastTotpUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_totp_used_at_utc");

                    b.Property<DateTimeOffset?>("LockoutEndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_ends_at_utc");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RecoveryCodeHashesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recovery_code_hashes_json");

                    b.Property<DateTimeOffset?>("RecoveryCodesUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recovery_codes_updated_at_utc");

                    b.Property<string>("RecoveryCodesUpdatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("recovery_codes_updated_by");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scopes_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TotpEnabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("totp_enabled_at_utc");

                    b.Property<string>("TotpSecret")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("totp_secret");

                    b.Property<DateTimeOffset?>("TotpUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("totp_updated_at_utc");

                    b.Property<string>("TotpUpdatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("totp_updated_by");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("updated_by");

                    b.HasKey("UserId");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_provider_access_operators_email");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_provider_access_operators_status");

                    b.ToTable("provider_access_operators", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudProviderBankDetailsEntity", b =>
                {
                    b.Property<string>("BankDetailsId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("bank_details_id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("account_number");

                    b.Property<string>("AccountTitle")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("account_title");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("bank_name");

                    b.Property<string>("BranchOrRoutingInfo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("branch_or_routing_info");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("iban");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("BankDetailsId");

                    b.ToTable("provider_bank_details", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlDeskEnvelopeReceiptEntity", b =>
                {
                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<string>("CloudReference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cloud_reference");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTimeOffset>("PreparedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prepared_at_utc");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("SignatureKeyId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("signature_key_id");

                    b.Property<string>("SignatureValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("signature_value");

                    b.Property<string>("SourceEnvironment")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_environment");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("subject_type");

                    b.HasKey("ReceiptId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_control_desk_envelope_receipts_accepted_idempotency_key")
                        .HasFilter("status = 'Accepted'");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_control_desk_envelope_receipts_message_id");

                    b.HasIndex("Status", "IdempotencyKey")
                        .HasDatabaseName("ix_control_desk_envelope_receipts_status_idempotency_key");

                    b.ToTable("control_desk_envelope_receipts", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudCommercialDocumentEntity", b =>
                {
                    b.HasOne("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientCommercialProjectionEntity", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudEntitlementBundleIssueEntity", b =>
                {
                    b.HasOne("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientInstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationCommandAcknowledgementEntity", b =>
                {
                    b.HasOne("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationCommandEntity", null)
                        .WithMany()
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationCommandEntity", b =>
                {
                    b.HasOne("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientInstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationDiagnosticReportEntity", b =>
                {
                    b.HasOne("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientInstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationHeartbeatEntity", b =>
                {
                    b.HasOne("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientInstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
