// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework;

#nullable disable

namespace SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(ControlCloudDbContext))]
    [Migration("20260701174028_AddInstallationCommandSignatures")]
    partial class AddInstallationCommandSignatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cloud")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientCommercialProjectionEntity", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<string>("ProjectionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("projection_json");

                    b.HasKey("ClientId");

                    b.HasIndex("LastUpdatedAtUtc")
                        .HasDatabaseName("ix_client_commercial_projections_last_updated_at_utc");

                    b.ToTable("client_commercial_projections", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientInstallationEntity", b =>
                {
                    b.Property<string>("InstallationId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("LastBundleIssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_bundle_issued_at_utc");

                    b.Property<long>("LatestEntitlementVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("latest_entitlement_version");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("InstallationId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_installations_client_id");

                    b.ToTable("client_installations", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudEntitlementBundleIssueEntity", b =>
                {
                    b.Property<Guid>("BundleIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("bundle_issue_id");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("algorithm");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("EntitlementSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("entitlement_snapshot_id");

                    b.Property<long>("EntitlementVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("entitlement_version");

                    b.Property<DateOnly>("GraceUntil")
                        .HasColumnType("date")
                        .HasColumnName("grace_until");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("key_id");

                    b.Property<DateOnly>("OfflineValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("offline_valid_until");

                    b.Property<DateOnly>("PaidUntil")
                        .HasColumnType("date")
                        .HasColumnName("paid_until");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_sha256");

                    b.Property<string>("SignatureValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("signature_value");

                    b.Property<DateOnly>("WarningStartsAt")
                        .HasColumnType("date")
                        .HasColumnName("warning_starts_at");

                    b.HasKey("BundleIssueId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_entitlement_bundle_issues_client_id");

                    b.HasIndex("InstallationId")
                        .HasDatabaseName("ix_entitlement_bundle_issues_installation_id");

                    b.HasIndex("InstallationId", "EntitlementVersion")
                        .HasDatabaseName("ix_entitlement_bundle_issues_installation_version");

                    b.ToTable("entitlement_bundle_issues", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationCommandAcknowledgementEntity", b =>
                {
                    b.Property<Guid>("AcknowledgementId")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledgement_id");

                    b.Property<DateTimeOffset>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<long>("CommandVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("command_version");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result_status");

                    b.HasKey("AcknowledgementId");

                    b.HasIndex("CommandId")
                        .HasDatabaseName("ix_installation_command_acknowledgements_command_id");

                    b.HasIndex("InstallationId")
                        .HasDatabaseName("ix_installation_command_acknowledgements_installation_id");

                    b.ToTable("installation_command_acknowledgements", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationCommandEntity", b =>
                {
                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<DateTimeOffset?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<string>("AcknowledgementDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("acknowledgement_detail");

                    b.Property<string>("AcknowledgementStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("acknowledgement_status");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("command_type");

                    b.Property<long>("CommandVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("command_version");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset?>("NotBeforeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_sha256");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at_utc");

                    b.Property<string>("SignatureAlgorithm")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("signature_algorithm");

                    b.Property<string>("SignatureKeyId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("signature_key_id");

                    b.Property<string>("SignatureValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("signature_value");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("CommandId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_installation_commands_client_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_installation_commands_idempotency_key");

                    b.HasIndex("InstallationId", "CommandVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_installation_commands_installation_version");

                    b.HasIndex("InstallationId", "Status")
                        .HasDatabaseName("ix_installation_commands_installation_status");

                    b.ToTable("installation_commands", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlDeskEnvelopeReceiptEntity", b =>
                {
                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<string>("CloudReference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cloud_reference");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTimeOffset>("PreparedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prepared_at_utc");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("SignatureKeyId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("signature_key_id");

                    b.Property<string>("SignatureValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("signature_value");

                    b.Property<string>("SourceEnvironment")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_environment");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("subject_type");

                    b.HasKey("ReceiptId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_control_desk_envelope_receipts_accepted_idempotency_key")
                        .HasFilter("status = 'Accepted'");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_control_desk_envelope_receipts_message_id");

                    b.HasIndex("Status", "IdempotencyKey")
                        .HasDatabaseName("ix_control_desk_envelope_receipts_status_idempotency_key");

                    b.ToTable("control_desk_envelope_receipts", "cloud");
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudEntitlementBundleIssueEntity", b =>
                {
                    b.HasOne("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientInstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationCommandAcknowledgementEntity", b =>
                {
                    b.HasOne("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationCommandEntity", null)
                        .WithMany()
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudInstallationCommandEntity", b =>
                {
                    b.HasOne("SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Entities.ControlCloudClientInstallationEntity", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
