// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework;

#nullable disable

namespace SafarSuite.ControlCloud.Infrastructure.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(ControlCloudDbContext))]
    [Migration("20260702130000_AddClientPortalIdentity")]
    partial class AddClientPortalIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
